# Generated by Django 5.2.10 on 2026-01-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deck',
            table='baralhos_flashcards',
        ),
        migrations.AlterModelTable(
            name='flashcard',
            table='cartoes_estudo',
        ),
        migrations.AlterModelTable(
            name='pomodorosession',
            table='sessoes_pomodoro',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tarefas',
        ),
    ]
