# Generated by Django 5.2.10 on 2026-01-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_message_table_alter_studygroup_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membership',
            table='membros_grupos',
        ),
    ]
